spring:
  profiles:
    active:
      - dev
---

spring:
  profiles: dev
  applicaion:
    name: microservicecloud-config-atguigu-dev
---

spring:
  profiles: test
  applicaion:
    name:microservicecloud-config-atguigu-test